# Diversity outbred mice

1. What is the DO study?
    1. Design
    1. Implementation
      - how many mice per generation? How many breeding?
      - where are the mice? ?Federal lab in Tennessee? 
1. Why is the DO design useful? What are traditional methods (ie, with inbred lines)? What are limitations of those traditional methods?
1. What challenges arise due to DO design?
1. What opportunities does DO study present?



The Diversity Outbred (DO) mouse population is a genetically heterogeneous stock that is used for mapping of quantitative trait loci for a wide range of phenotypes. It is now in its 18th generation [check this!]. The DO mouse population is maintained by random mating among a breeding population of about 175 mice (where siblings aren't permitted to mate with each other). 

The study design began with mice from the eight Collaborative Cross (CC) inbred founder lines, [list the 8 lines here!]. These mice randomly mated to create the first generation of DO mice. From each first litter of first generation DO mice, the biologists selected two mice at random to be members of the breeding population that would give rise to the second generation of DO mice. Researchers perpetuated this breeding scheme to create subsequent generations of DO mice.

Each mouse in the DO study possesses a unique mixture of founder haplotypes. We'll refer to a pair of haplotypes at a single locus and in a single mouse as a "diplotype". The precise nature of a given individual's diplotypes depends on the positions of meiotic crossover events. Combinatorics tells us that, for 8 inbred founder strains, there are $\binom{8}{1} = 8$ homozygote diplotypes and $\binom{8}{2} = 28$ heterozygous diplotypes for each locus. Inference of the 36 diplotype probabilities at each locus is a major prerequisite towards QTL mapping. In our study, Karl Broman implemented (in R/qtl2geno and related packages) a hidden Markov model (HMM) to infer diplotype probabilities from MegaMUGA SNP microarray intensities.

Compared to more traditional QTL studies, which typically involve inbred lines, the DO study offers a population with a much greater degree of genetic diversity. Mice from each successive generation show greater extents of genetic diversity due to each generation's meiotic cross-over events. Study designers expected that greater genetic diversity would lead to greater phenotypic diversity among mice. This is indeed the case in the phenotypes studied to date. 


