# Linear mixed effects models

One important confounder in QTL studies is relatedness of subjects. Relatedness becomes apparent in QTL studies as 

Key reference (including discussion of likelihood equations): [@kang2008efficient] ie, the EMMA paper.

Linear mixed effects models are widely used in genome-wide association studies and QTL studies to account for relatedness.

Univariate models of each quantitative trait identified initial loci of interest. The models were fitted via restricted maximum likelihood methods (REML). Karl Broman has implemented these methods in the R/qtl2scan and related packages.

The univariate model that we use for QTL mapping is:

$Y = X\beta + \epsilon$

where $Var (\epsilon) = \sigma^2_g K + \sigma^2_e I$
where $K$ is a known kinship matrix and $I$ is the identity matrix.




1. Why do they use a linear mixed effects model? 

    1. What are its strengths & weaknesses?

1. How do they fit the model?

The linear mixed effects model is fitted by restricted maximum likelihood methods. 